Hotfix 0.8.5 (#3824)
* fix(cli): correctly handle `.env` files again

* feat(ci): add functionality tests for sqlx-cli (MySQL)

* feat(ci): add functionality tests for sqlx-cli (Postgres)

* feat(ci): add functionality tests for sqlx-cli (SQLite)

* chore: prepare 0.8.5 release

* feat(ci): run `test-attr` tests twice to catch #3825

* fix: correct bugs in MySQL implementation of `#[sqlx::test]`

diff --git a/.github/workflows/sqlx-cli.yml b/.github/workflows/sqlx-cli.yml
--- a/.github/workflows/sqlx-cli.yml
+++ b/.github/workflows/sqlx-cli.yml
@@ -33,8 +33,8 @@ jobs:
           --manifest-path sqlx-cli/Cargo.toml
           --target-dir target/beta/
 
-  test:
-    name: Test
+  integration-test:
+    name: Integration Test
     runs-on: ${{ matrix.os }}
 
     strategy:
@@ -56,6 +56,235 @@ jobs:
       - uses: Swatinem/rust-cache@v2
 
       - run: cargo test --manifest-path sqlx-cli/Cargo.toml
+
+  test-mysql:
+    name: Functional Test (MySQL)
+    runs-on: ubuntu-latest
+    # Deliberately not using `tests/docker-compose.yml` because that sets up the database automatically.
+    services:
+      mysql:
+        image: mysql:8
+        ports:
+          - 3306:3306
+        env:
+          MYSQL_ROOT_PASSWORD: password
+    env:
+      BASE_URL: mysql://root:password@localhost
+
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Setup Rust
+        run: rustup show active-toolchain || rustup toolchain install
+
+      - uses: Swatinem/rust-cache@v2
+
+      - name: Install SQLx-CLI
+        run:
+          cargo install --locked --debug --path sqlx-cli
+
+      - name: Basic Test
+        env:
+          DATABASE_URL: ${{ env.BASE_URL }}/test1
+        run: |
+          sqlx db setup --source=tests/mysql/migrations
+          
+          sqlx mig info --source=tests/mysql/migrations
+          
+          sqlx db drop -y
+
+      - name: Test .env
+        run: |
+          echo "DATABASE_URL=${{ env.BASE_URL }}/test2" > .env
+          
+          sqlx db setup --source=tests/mysql/migrations
+          
+          sqlx mig info --source=tests/mysql/migrations
+          
+          sqlx db drop -y
+
+      - name: Test --no-dotenv
+        run: |
+          # Allow subcommands to fail
+          set +e
+          
+          echo "DATABASE_URL=${{ env.BASE_URL }}/test3" > .env
+          
+          ERROR=$(sqlx db setup --no-dotenv --source=tests/mysql/migrations)
+          
+          if [[ "$ERROR" == *"--database-url"* ]]; then
+            exit 0
+          else
+            echo "Unexpected error from sqlx-cli: $ERROR"
+            exit 1
+          fi
+
+      - name: Test Reversible Migrations
+        env:
+          DATABASE_URL: ${{ env.BASE_URL }}/test4
+        run: |
+          sqlx db setup --source=tests/mysql/migrations_reversible
+          
+          INFO_BEFORE=$(sqlx mig info --source=tests/mysql/migrations_reversible)
+          
+          sqlx mig revert --target-version=0 --source=tests/mysql/migrations_reversible
+          
+          INFO_AFTER=$(sqlx mig info --source=tests/mysql/migrations_reversible)
+          
+          if [[ "$INFO_BEFORE" == "$INFO_AFTER" ]]; then
+            echo "Error: migration info is identical before and after migrating: $INFO_BEFORE"
+            exit 1
+          fi
+
+  test-postgres:
+    name: Functional Test (PostgreSQL)
+    runs-on: ubuntu-latest
+    # Deliberately not using `tests/docker-compose.yml` because that sets up the database automatically.
+    services:
+      mysql:
+        image: postgres:17
+        ports:
+          - 5432:5432
+        env:
+          POSTGRES_PASSWORD: password
+    env:
+      BASE_URL: postgres://postgres:password@localhost
+
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Setup Rust
+        run: rustup show active-toolchain || rustup toolchain install
+
+      - uses: Swatinem/rust-cache@v2
+
+      - name: Install SQLx-CLI
+        run:
+          cargo install --locked --debug --path sqlx-cli
+
+      - name: Basic Test
+        env:
+          DATABASE_URL: ${{ env.BASE_URL }}/test1
+        run: |
+          sqlx db setup --source=tests/postgres/migrations
+          
+          sqlx mig info --source=tests/postgres/migrations
+          
+          sqlx db drop -y
+
+      - name: Test .env
+        run: |
+          echo "DATABASE_URL=${{ env.BASE_URL }}/test2" > .env
+          
+          sqlx db setup --source=tests/postgres/migrations
+          
+          sqlx mig info --source=tests/postgres/migrations
+          
+          sqlx db drop -y
+
+      - name: Test --no-dotenv
+        run: |
+          # Allow subcommands to fail
+          set +e
+          
+          echo "DATABASE_URL=${{ env.BASE_URL }}/test3" > .env
+          
+          ERROR=$(sqlx db setup --no-dotenv --source=tests/postgres/migrations)
+          
+          if [[ "$ERROR" == *"--database-url"* ]]; then
+            exit 0
+          else
+            echo "Unexpected error from sqlx-cli: $ERROR"
+            exit 1
+          fi
+
+      - name: Test Reversible Migrations
+        env:
+          DATABASE_URL: ${{ env.BASE_URL }}/test4
+        run: |
+          sqlx db setup --source=tests/postgres/migrations_reversible
+          
+          INFO_BEFORE=$(sqlx mig info --source=tests/postgres/migrations_reversible)
+          
+          sqlx mig revert --target-version=0 --source=tests/postgres/migrations_reversible
+          
+          INFO_AFTER=$(sqlx mig info --source=tests/postgres/migrations_reversible)
+          
+          if [[ "$INFO_BEFORE" == "$INFO_AFTER" ]]; then
+            echo "Error: migration info is identical before and after migrating: $INFO_BEFORE"
+            exit 1
+          fi
+
+  test-sqlite:
+    name: Functional Test (SQLite)
+    runs-on: ubuntu-latest
+    env:
+      BASE_URL: sqlite://.
+
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Setup Rust
+        run: rustup show active-toolchain || rustup toolchain install
+
+      - uses: Swatinem/rust-cache@v2
+
+      - name: Install SQLx-CLI
+        run:
+          cargo install --locked --debug --path sqlx-cli
+
+      - name: Basic Test
+        env:
+          DATABASE_URL: ${{ env.BASE_URL }}/test1
+        run: |
+          sqlx db setup --source=tests/sqlite/migrations
+          
+          sqlx mig info --source=tests/sqlite/migrations
+          
+          sqlx db drop -y
+
+      - name: Test .env
+        run: |
+          echo "DATABASE_URL=${{ env.BASE_URL }}/test2" > .env
+          
+          sqlx db setup --source=tests/sqlite/migrations
+          
+          sqlx mig info --source=tests/sqlite/migrations
+          
+          sqlx db drop -y
+
+      - name: Test --no-dotenv
+        run: |
+          # Allow subcommands to fail
+          set +e
+          
+          echo "DATABASE_URL=${{ env.BASE_URL }}/test3" > .env
+          
+          ERROR=$(sqlx db setup --no-dotenv --source=tests/sqlite/migrations)
+          
+          if [[ "$ERROR" == *"--database-url"* ]]; then
+            exit 0
+          else
+            echo "Unexpected error from sqlx-cli: $ERROR"
+            exit 1
+          fi
+
+      - name: Test Reversible Migrations
+        env:
+          DATABASE_URL: ${{ env.BASE_URL }}/test4
+        run: |
+          sqlx db setup --source=tests/sqlite/migrations_reversible
+          
+          INFO_BEFORE=$(sqlx mig info --source=tests/sqlite/migrations_reversible)
+          
+          sqlx mig revert --target-version=0 --source=tests/sqlite/migrations_reversible
+          
+          INFO_AFTER=$(sqlx mig info --source=tests/sqlite/migrations_reversible)
+          
+          if [[ "$INFO_BEFORE" == "$INFO_AFTER" ]]; then
+            echo "Error: migration info is identical before and after migrating: $INFO_BEFORE"
+            exit 1
+          fi
 
   build:
     name: Build
